### ISSUE TITLE
Can I take this mod to China?

### ISSUE THREAD

**Issue by kaoyu555666777** [bl4ckscor3/WoolButtons#2]
Hallo,bl4ckscor3.I am a Chinese player.I like your mod Wool Buttons very much.I think other Chinese players like it,too.So,I want to take it to "www.mcbbs.net".It is the largest minecraft forum in China.I will put the curseforge link and GitHub link on it.And I'll put your name there.Thank you very much!

**Comment by bl4ckscor3** [comment]
It's ok, if you do not reupload the files of my mod, and the only way to download it is via my CurseForge page.
